import disneyPlusImg from '@/assets/images/disney-plus.png';
import millieImg from '@/assets/images/millie.png';
import netflixImg from '@/assets/images/netflix.png';
import tvingImg from '@/assets/images/tving.png';
import wavveImg from '@/assets/images/wavve.png';
import youtubeImg from '@/assets/images/youtube-premium.png';

import type { OTTType, Plan, SortTarget } from './types';

export const OTT_IMAGES: Record<OTTType, string> = {
  NETFLIX: netflixImg,
  YOUTUBE_PREMIUM: youtubeImg,
  'DISNEY+': disneyPlusImg,
  WAVVE: wavveImg,
  TVING: tvingImg,
  MILLIE: millieImg,
};

export const SORT_LABELS: Record<SortTarget, string> = {
  price: '월정액',
  dataAmountMb: '데이터',
  overageSpeedMbps: '속도',
  voiceMinutes: '음성통화',
  smsIncluded: '문자',
};

export const OTT_LABELS: Record<OTTType, string> = {
  NETFLIX: '넷플릭스',
  YOUTUBE_PREMIUM: '유튜브 프리미엄',
  'DISNEY+': '디즈니+',
  WAVVE: '웨이브',
  TVING: '티빙',
  MILLIE: '밀리의 서재',
};

export const MOCK_PLANS: Plan[] = [
  {
    id: 1,
    name: '5G 슈퍼플랜',
    price: 95000,
    dataAmountMb: 0, // 0 = 무제한
    overageSpeedMbps: 5,
    voiceMinutes: -1, // -1 = 무제한
    smsIncluded: 200,
    networkType: '5G',
    subscriptionServices: ['NETFLIX', 'YOUTUBE_PREMIUM'],
    badges: [],
  },
  {
    id: 2,
    name: '5G 스탠다드',
    price: 75000,
    dataAmountMb: 100000, // 100GB
    overageSpeedMbps: 3,
    voiceMinutes: 1000,
    smsIncluded: 100,
    networkType: '5G',
    subscriptionServices: ['DISNEY+'],
    badges: [],
  },
  {
    id: 3,
    name: 'LTE 베이직',
    price: 45000,
    dataAmountMb: 50000, // 50GB
    overageSpeedMbps: 1,
    voiceMinutes: 500,
    smsIncluded: 50,
    networkType: 'LTE',
    subscriptionServices: ['WAVVE', 'TVING'],
    badges: [],
  },
  {
    id: 4,
    name: '5G 프리미엄',
    price: 120000,
    dataAmountMb: 0,
    overageSpeedMbps: 10,
    voiceMinutes: -1,
    smsIncluded: 300,
    networkType: '5G',
    subscriptionServices: ['NETFLIX', 'YOUTUBE_PREMIUM', 'DISNEY+'],
    badges: [],
  },
  {
    id: 5,
    name: 'LTE 라이트',
    price: 35000,
    dataAmountMb: 30000, // 30GB
    overageSpeedMbps: 0.5,
    voiceMinutes: 300,
    smsIncluded: 30,
    networkType: 'LTE',
    subscriptionServices: [],
    badges: [],
  },
  {
    id: 6,
    name: '5G 미디엄',
    price: 65000,
    dataAmountMb: 80000, // 80GB
    overageSpeedMbps: 2,
    voiceMinutes: 800,
    smsIncluded: 80,
    networkType: '5G',
    subscriptionServices: ['MILLIE'],
    badges: [],
  },
  {
    id: 7,
    name: 'LTE 스탠다드',
    price: 55000,
    dataAmountMb: 60000, // 60GB
    overageSpeedMbps: 1.5,
    voiceMinutes: 600,
    smsIncluded: 60,
    networkType: 'LTE',
    subscriptionServices: ['TVING'],
    badges: [],
  },
  {
    id: 8,
    name: '5G 울트라',
    price: 150000,
    dataAmountMb: 0,
    overageSpeedMbps: 15,
    voiceMinutes: -1,
    smsIncluded: 500,
    networkType: '5G',
    subscriptionServices: [
      'NETFLIX',
      'YOUTUBE_PREMIUM',
      'DISNEY+',
      'WAVVE',
      'TVING',
    ],
    badges: [],
  },
  {
    id: 9,
    name: '5G 스마트',
    price: 85000,
    dataAmountMb: 0,
    overageSpeedMbps: 4,
    voiceMinutes: -1,
    smsIncluded: 150,
    networkType: '5G',
    subscriptionServices: ['YOUTUBE_PREMIUM', 'WAVVE'],
    badges: ['인기'],
  },
  {
    id: 10,
    name: 'LTE 프리미엄',
    price: 60000,
    dataAmountMb: 70000,
    overageSpeedMbps: 1.2,
    voiceMinutes: 700,
    smsIncluded: 70,
    networkType: 'LTE',
    subscriptionServices: ['TVING'],
    badges: [],
  },
  {
    id: 11,
    name: '5G 스타터',
    price: 55000,
    dataAmountMb: 40000,
    overageSpeedMbps: 1.5,
    voiceMinutes: 400,
    smsIncluded: 40,
    networkType: '5G',
    subscriptionServices: [],
    badges: ['신규'],
  },
  {
    id: 12,
    name: 'LTE 플러스',
    price: 50000,
    dataAmountMb: 55000,
    overageSpeedMbps: 1,
    voiceMinutes: 550,
    smsIncluded: 55,
    networkType: 'LTE',
    subscriptionServices: ['WAVVE'],
    badges: [],
  },
  {
    id: 13,
    name: '5G 엔터테인먼트',
    price: 110000,
    dataAmountMb: 0,
    overageSpeedMbps: 8,
    voiceMinutes: -1,
    smsIncluded: 400,
    networkType: '5G',
    subscriptionServices: ['NETFLIX', 'YOUTUBE_PREMIUM', 'DISNEY+', 'TVING'],
    badges: ['추천'],
  },
  {
    id: 14,
    name: 'LTE 이코노미',
    price: 30000,
    dataAmountMb: 25000,
    overageSpeedMbps: 0.3,
    voiceMinutes: 250,
    smsIncluded: 25,
    networkType: 'LTE',
    subscriptionServices: [],
    badges: ['저렴'],
  },
  {
    id: 15,
    name: '5G 비즈니스',
    price: 130000,
    dataAmountMb: 0,
    overageSpeedMbps: 12,
    voiceMinutes: -1,
    smsIncluded: 600,
    networkType: '5G',
    subscriptionServices: [
      'NETFLIX',
      'YOUTUBE_PREMIUM',
      'DISNEY+',
      'WAVVE',
      'TVING',
      'MILLIE',
    ],
    badges: ['프리미엄'],
  },
  {
    id: 16,
    name: 'LTE 미디엄',
    price: 48000,
    dataAmountMb: 45000,
    overageSpeedMbps: 0.8,
    voiceMinutes: 450,
    smsIncluded: 45,
    networkType: 'LTE',
    subscriptionServices: [],
    badges: [],
  },
  {
    id: 17,
    name: '5G 게이밍',
    price: 100000,
    dataAmountMb: 0,
    overageSpeedMbps: 7,
    voiceMinutes: -1,
    smsIncluded: 350,
    networkType: '5G',
    subscriptionServices: ['YOUTUBE_PREMIUM'],
    badges: ['특화'],
  },
  {
    id: 18,
    name: 'LTE 스마트',
    price: 42000,
    dataAmountMb: 40000,
    overageSpeedMbps: 0.7,
    voiceMinutes: 400,
    smsIncluded: 40,
    networkType: 'LTE',
    subscriptionServices: ['WAVVE'],
    badges: [],
  },
  {
    id: 19,
    name: '5G 패밀리',
    price: 140000,
    dataAmountMb: 0,
    overageSpeedMbps: 9,
    voiceMinutes: -1,
    smsIncluded: 450,
    networkType: '5G',
    subscriptionServices: ['NETFLIX', 'YOUTUBE_PREMIUM', 'DISNEY+', 'WAVVE'],
    badges: ['가족'],
  },
  {
    id: 20,
    name: 'LTE 베이직 플러스',
    price: 38000,
    dataAmountMb: 35000,
    overageSpeedMbps: 0.5,
    voiceMinutes: 350,
    smsIncluded: 35,
    networkType: 'LTE',
    subscriptionServices: [],
    badges: [],
  },
  {
    id: 21,
    name: '5G 프로',
    price: 125000,
    dataAmountMb: 0,
    overageSpeedMbps: 11,
    voiceMinutes: -1,
    smsIncluded: 550,
    networkType: '5G',
    subscriptionServices: ['NETFLIX', 'YOUTUBE_PREMIUM', 'DISNEY+', 'TVING'],
    badges: ['프로'],
  },
  {
    id: 22,
    name: 'LTE 컴팩트',
    price: 32000,
    dataAmountMb: 28000,
    overageSpeedMbps: 0.4,
    voiceMinutes: 280,
    smsIncluded: 28,
    networkType: 'LTE',
    subscriptionServices: [],
    badges: ['경제'],
  },
  {
    id: 23,
    name: '5G 엔터프라이즈',
    price: 160000,
    dataAmountMb: 0,
    overageSpeedMbps: 20,
    voiceMinutes: -1,
    smsIncluded: 1000,
    networkType: '5G',
    subscriptionServices: [
      'NETFLIX',
      'YOUTUBE_PREMIUM',
      'DISNEY+',
      'WAVVE',
      'TVING',
      'MILLIE',
    ],
    badges: ['최고급'],
  },
  {
    id: 24,
    name: 'LTE 프리미엄 플러스',
    price: 65000,
    dataAmountMb: 80000,
    overageSpeedMbps: 2,
    voiceMinutes: 800,
    smsIncluded: 80,
    networkType: 'LTE',
    subscriptionServices: ['TVING', 'WAVVE'],
    badges: [],
  },
  {
    id: 25,
    name: '5G 스트리밍',
    price: 90000,
    dataAmountMb: 0,
    overageSpeedMbps: 6,
    voiceMinutes: -1,
    smsIncluded: 300,
    networkType: '5G',
    subscriptionServices: ['NETFLIX', 'YOUTUBE_PREMIUM', 'DISNEY+'],
    badges: ['스트리밍'],
  },
  {
    id: 26,
    name: 'LTE 스탠다드 플러스',
    price: 58000,
    dataAmountMb: 65000,
    overageSpeedMbps: 1.8,
    voiceMinutes: 650,
    smsIncluded: 65,
    networkType: 'LTE',
    subscriptionServices: ['TVING'],
    badges: [],
  },
  {
    id: 27,
    name: '5G 라이트',
    price: 60000,
    dataAmountMb: 50000,
    overageSpeedMbps: 2.5,
    voiceMinutes: 500,
    smsIncluded: 50,
    networkType: '5G',
    subscriptionServices: ['YOUTUBE_PREMIUM'],
    badges: ['신규'],
  },
  {
    id: 28,
    name: 'LTE 이코노미 플러스',
    price: 40000,
    dataAmountMb: 38000,
    overageSpeedMbps: 0.6,
    voiceMinutes: 380,
    smsIncluded: 38,
    networkType: 'LTE',
    subscriptionServices: [],
    badges: ['저렴'],
  },
];
