export const faqs = [
  {
    id: 'f1',
    category: '인터넷/TV',
    isTop10: true,
    title: '[인터넷/TV] 갑자기 인터넷이 되지 않습니다',
    content: '공유기와 모뎀 전원을 껐다 켜보신 후 5분 뒤에 다시 시도해주세요.',
  },
  {
    id: 'f2',
    category: '모바일',
    isTop10: true,
    title: '[모바일] 홈페이지에서 휴대폰 번호를 변경하고 싶어요',
    content: '마이페이지 > 정보 관리 메뉴에서 본인인증 후 변경 가능합니다.',
  },
  {
    id: 'f3',
    category: '결제/관리',
    isTop10: true,
    title: '[결제/관리] 휴대폰 결제 차단/해제 방법은?',
    content: '고객센터 앱 내 결제 관리 메뉴에서 즉시 설정 가능합니다.',
  },
  {
    id: 'f4',
    category: '결제/관리',
    isTop10: true,
    title: '[결제/관리] 세금계산서 발급 방법',
    content: '홈페이지 납부 내역 메뉴에서 직접 출력이 가능합니다.',
  },
  {
    id: 'f5',
    category: '결제/관리',
    isTop10: true,
    title: '[결제/관리] 휴대폰 결제 한도 조정 안내',
    content: '월 최대 100만원 내에서 본인의 등급에 따라 조정 가능합니다.',
  },
  {
    id: 'f6',
    category: '모바일',
    isTop10: true,
    title: '[모바일] 휴대폰 일시정지 신청',
    content: '홈페이지나 앱에서 정지 기간을 설정하여 신청하세요.',
  },
  {
    id: 'f7',
    category: '모바일',
    isTop10: true,
    title: '[모바일] 분실 시 일시정지 방법',
    content: '분실 즉시 114 전화를 통해 즉각 신고하시길 권장합니다.',
  },
  {
    id: 'f8',
    category: '서비스안내',
    isTop10: true,
    title: '[서비스안내] 해외 출장 시 일시정지 서류',
    content: '항공권 사본이나 출국 증명 서류가 필요합니다.',
  },
  {
    id: 'f9',
    category: '결제/관리',
    isTop10: true,
    title: '[결제/관리] 청구요금 상세 내역 확인',
    content: '이메일 명세서나 앱 내 요금 상세 메뉴에서 확인 가능합니다.',
  },
  {
    id: 'f10',
    category: '결제/관리',
    isTop10: true,
    title: '[결제/관리] 미납 요금 납부 후 이용 재개',
    content: '완납 후 통상 5~10분 이내에 자동으로 해제됩니다.',
  },
  {
    id: 'f11',
    category: '모바일',
    isTop10: false,
    title: '[모바일] 유심(USIM) 기기변경 안내',
    content:
      '기존 유심을 새 단말기에 장착 후 2~3회 재부팅하면 자동 등록됩니다.',
  },
  {
    id: 'f12',
    category: '인터넷/TV',
    isTop10: false,
    title: '[인터넷/TV] 셋톱박스 재부팅 가이드',
    content: '셋톱박스 뒤편의 전원 스위치를 껐다가 10초 후 다시 켜주세요.',
  },
  {
    id: 'f13',
    category: '모바일',
    isTop10: false,
    title: '[모바일] 번호이동 시 기존 통신사 자동 해지 여부',
    content: '새로운 통신사 개통 시 기존 통신사는 자동으로 해지됩니다.',
  },
  {
    id: 'f14',
    category: '모바일',
    isTop10: false,
    title: '[모바일] 선택약정할인 승계 및 재가입',
    content: '기존 약정 기간 6개월 미만 잔여 시 위약금 없이 재가입 가능합니다.',
  },
  {
    id: 'f15',
    category: '인터넷/TV',
    isTop10: false,
    title: '[인터넷/TV] 이사할 때 이전 설치 신청 시기',
    content: '원하는 날짜 설치를 위해 최소 1주일 전 예약이 필요합니다.',
  },
  {
    id: 'f16',
    category: '결제/관리',
    isTop10: false,
    title: '[결제/관리] 미납 요금 시 휴대폰 결제 이용',
    content: '미납 요금 전액 납부 후 익일부터 정상 이용 가능합니다.',
  },
  {
    id: 'f17',
    category: '결제/관리',
    isTop10: false,
    title: '[결제/관리] 가족 결합 할인 신청 방법',
    content: '가족관계증명서 지참 후 대리점 방문 또는 앱 업로드가 필요합니다.',
  },
  {
    id: 'f18',
    category: '서비스안내',
    isTop10: false,
    title: '[가입/변경] 일시정지 신청 및 해제 방법',
    content: '연간 최대 180일까지 가능하며, 앱을 통해 즉시 처리 가능합니다.',
  },
  {
    id: 'f19',
    category: '서비스안내',
    isTop10: false,
    title: '[해지] 온라인으로 해지 신청 가능 여부',
    content: '본인인증 완료 시 홈페이지 마이페이지에서 신청 가능합니다.',
  },
  {
    id: 'f20',
    category: '서비스안내',
    isTop10: false,
    title: '[기기변경] 중고폰/자급제폰 기기변경 방법',
    content: '기존 유심을 새 기기에 꽂기만 하면 즉시 사용 가능합니다.',
  },
  {
    id: 'f21',
    category: '서비스안내',
    isTop10: false,
    title: '[명의변경] 가족 간 명의 변경 절차',
    content: '양도인/양수인 모두 신분증 지참 후 대리점 방문이 원칙입니다.',
  },
];
