export const PAGE_PATHS = {
  LOGIN: '/',
  LOGIN_FORM: '/login/form',
  SIGNUP: '/signup',
  HOME: '/home',
  SUMMARY: '/summary',
  ADMIN: '/admin',
  PLAN: '/plan',
  SUBSCRIBE: '/subscribe',
  PERSONALITY_TEST: '/personality-test',
  CHAT: '/chat',
  CHAT_MANUAL: '/chat/manual',
  MYPAGE: '/mypage',
  CUSTOMER_SERVICE: '/customer-service',
  ARMY_GUIDE: '/customer-service/army',
  PROXY_GUIDE: '/customer-service/proxy',
  MINOR_GUIDE: '/customer-service/minor',
};
