export const PAGE_PATHS = {
  LOGIN: '/',
  LOGIN_FORM: '/login/form',
  SIGNUP: '/signup',
  HOME: '/home',
  SUMMARY: '/summary',
  ADMIN: '/admin',
  PLAN: '/plan',
  PLAN_DETAIL: '/plan/:id',
  PLAN_COMPARE: '/plan/compare',
  SUBSCRIBE: '/subscribe',
  SUBSCRIBE_DETAIL: '/subscribe/:id',
  PERSONALITY_TEST: '/personality-test',
  CHAT: '/chat',
  CHAT_MANUAL: '/chat/manual',
  MYPAGE: '/mypage',
  COUNSEL: '/counsel',
  CUSTOMER_SERVICE: '/customer',
  ARMY_GUIDE: '/customer/army',
  PROXY_GUIDE: '/customer/proxy',
  MINOR_GUIDE: '/customer/minor',
  LOGIN_GUARD: '/login-guard',
  TIPS_GUIDE: '/mypage/tips',
};
